name: polymrl
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.7.14
  - cairo=1.18.4
  - chardet=5.2.0
  - contourpy=1.3.2
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.59.0
  - freetype=2.13.3
  - freetype-py=2.3.0
  - greenlet=3.2.3
  - icu=75.1
  - keyutils=1.6.1
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libblas=3.9.0
  - libboost=1.86.0
  - libboost-python=1.86.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libdeflate=1.24
  - libedit=3.1.20250104
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libglib=2.84.2
  - libgomp=15.1.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libntlm=1.8
  - libopenblas=0.3.30
  - libpng=1.6.50
  - libpq=17.5
  - librdkit=2025.03.4
  - libsqlite=3.50.3
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.13.8
  - libzlib=1.3.1
  - matplotlib-base=3.10.3
  - munkres=1.1.4
  - ncurses=6.5
  - openbabel=3.1.1
  - openjpeg=2.5.3
  - openldap=2.6.10
  - openssl=3.5.1
  - packaging=25.0
  - pandas=2.3.1
  - pcre2=10.45
  - pillow=11.3.0
  - pip=25.1.1
  - pixman=0.46.4
  - pthread-stubs=0.4
  - pycairo=1.28.0
  - pyparsing=3.2.3
  - python=3.12.11
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.12
  - pytz=2025.2
  - qhull=2020.2
  - rdkit=2025.03.4
  - readline=8.2
  - reportlab=4.4.1
  - rlpycairo=0.2.0
  - setuptools=80.9.0
  - sqlalchemy=2.0.41
  - tk=8.6.13
  - typing-extensions=4.14.1
  - typing_extensions=4.14.1
  - tzdata=2025b
  - unicodedata2=16.0.0
  - wheel=0.45.1
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - zstd=1.5.7
  - pip:
      - absl-py==2.1.0
      - addict==2.4.0
      - aiobotocore==2.23.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.14
      - aioitertools==0.12.0
      - aiosignal==1.4.0
      - alabaster==1.0.0
      - altair==5.5.0
      - annotated-types==0.7.0
      - anthropic==0.58.2
      - anyio==4.9.0
      - apricot-select==0.6.1
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - astunparse==1.6.3
      - async-lru==2.0.5
      - attrs==25.3.0
      - babel==2.17.0
      - backcall==0.2.0
      - backoff==2.2.1
      - beautifulsoup4==4.13.4
      - biopandas==0.5.1
      - biopython==1.85
      - bleach==6.2.0
      - blinker==1.9.0
      - blis==1.2.1
      - boto3==1.38.46
      - botocore==1.38.46
      - cachetools==6.1.0
      - catalogue==2.0.10
      - certifi==2025.7.14
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - chembench==0.3.0
      - click==8.1.7
      - cloudpathlib==0.21.1
      - comm==0.2.3
      - confection==0.1.5
      - cymem==2.0.11
      - dataclasses-json==0.6.7
      - datasets==4.0.0
      - debugpy==1.8.16
      - decorator==5.2.1
      - deepchem==2.5.0
      - defusedxml==0.7.1
      - dill==0.3.8
      - distro==1.9.0
      - docutils==0.21.2
      - einops==0.8.1
      - et-xmlfile==2.0.0
      - executing==2.2.0
      - fastcore==1.8.5
      - fastjsonschema==2.21.2
      - fcd-torch==1.0.7
      - filelock==3.18.0
      - fire==0.7.0
      - flatbuffers==25.2.10
      - flexcache==0.3
      - flexparser==0.4
      - fqdn==1.5.1
      - frozenlist==1.7.0
      - fsspec==2024.6.1
      - ftfy==6.3.1
      - gast==0.6.0
      - git-filter-repo==2.47.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-pasta==0.2.0
      - groq==0.30.0
      - grpcio==1.73.1
      - h11==0.16.0
      - h5py==3.14.0
      - hdbscan==0.8.40
      - httpcore==1.0.9
      - httpx==0.28.1
      - httpx-sse==0.4.1
      - huggingface-hub==0.27.1
      - idna==3.10
      - ignite==1.1.0
      - imageio==2.33.1
      - imagesize==1.4.1
      - importlib-metadata==8.7.0
      - iniconfig==2.1.0
      - ipykernel==6.30.1
      - ipython==8.12.3
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - jiter==0.10.0
      - jmespath==1.0.1
      - joblib==1.4.2
      - json5==0.12.1
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.25.0
      - jsonschema-specifications==2025.4.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.8.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.6
      - jupyter-server==2.16.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.6
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - keras==3.10.0
      - langchain==0.3.26
      - langchain-anthropic==0.3.17
      - langchain-community==0.3.27
      - langchain-core==0.3.70
      - langchain-groq==0.3.6
      - langchain-text-splitters==0.3.8
      - langcodes==3.5.0
      - langsmith==0.4.8
      - language-data==1.3.0
      - lark==1.2.2
      - libclang==18.1.1
      - lie-learn==0.0.2
      - lightning-utilities==0.14.3
      - litellm==1.74.7
      - llvmlite==0.44.0
      - lmdb==1.4.1
      - loguru==0.7.3
      - looseversion==1.1.2
      - marisa-trie==1.2.1
      - markdown==3.8.2
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - marshmallow==3.26.1
      - matplotlib-inline==0.1.7
      - mdtraj==1.11.0
      - mdurl==0.1.2
      - mistune==3.1.3
      - ml-dtypes==0.4.1
      - mmtf-python==1.1.3
      - mpmath==1.3.0
      - msgpack==1.0.8
      - multidict==6.6.3
      - multiprocess==0.70.16
      - murmurhash==1.0.13
      - mypy-extensions==1.1.0
      - namex==0.1.0
      - narwhals==1.48.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.3
      - nose==1.3.7
      - notebook==7.4.5
      - notebook-shim==0.2.4
      - numba==0.61.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-ml-py==12.575.51
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - openai==1.97.0
      - openpyxl==3.1.5
      - opt-einsum==3.4.0
      - optree==0.16.0
      - orjson==3.11.0
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pint==0.24.4
      - platformdirs==4.3.8
      - pluggy==1.6.0
      - pomegranate==1.1.2
      - preshed==3.0.10
      - prometheus-client==0.22.1
      - prompt-toolkit==3.0.51
      - propcache==0.3.2
      - protobuf==5.29.5
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==21.0.0
      - pycparser==2.22
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydantic-settings==2.10.1
      - pydeck==0.9.1
      - pygments==2.19.2
      - pyiast==1.4.3
      - pynvml==12.0.0
      - pytest==7.4.4
      - python-dotenv==1.1.1
      - python-json-logger==3.3.0
      - pytorch-lightning==2.5.1.post0
      - pyyaml==6.0.1
      - pyzmq==27.0.1
      - radonpy-pypi==0.2.9
      - referencing==0.36.2
      - regex==2024.9.11
      - requests==2.32.4
      - requests-toolbelt==1.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==14.0.0
      - roman-numerals-py==3.1.0
      - rpds-py==0.26.0
      - s3fs==2024.6.1
      - s3transfer==0.13.1
      - safetensors==0.5.3
      - scikit-learn==1.7.1
      - scipy==1.16.0
      - seaborn==0.13.2
      - send2trash==1.8.3
      - sentencepiece==0.2.0
      - sentry-sdk==2.33.1
      - seqeval==1.2.2
      - shellingham==1.5.4
      - simpletransformers==0.70.1
      - six==1.16.0
      - smart-open==7.3.0.post1
      - smmap==5.0.2
      - sniffio==1.3.1
      - snowballstemmer==3.0.1
      - soupsieve==2.7
      - spacy==3.8.7
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - sphinx==8.2.3
      - sphinx-rtd-theme==3.0.2
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jquery==4.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - srsly==2.5.1
      - stack-data==0.6.3
      - streamlit==1.47.0
      - sympy==1.13.1
      - tabulate==0.9.0
      - tenacity==8.3.0
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.4
      - termcolor==3.1.0
      - terminado==0.18.1
      - thinc==8.3.4
      - threadpoolctl==3.6.0
      - tiktoken==0.9.0
      - tinycss2==1.4.0
      - tokenizers==0.21.2
      - toml==0.10.2
      - torch==2.6.0
      - torchinfo==1.8.0
      - torchmetrics==1.7.4
      - torchsummary==1.5.1
      - torchvision==0.21.0
      - tornado==6.5.1
      - tqdm==4.66.5
      - traitlets==5.14.3
      - transformers==4.50.3
      - triton==3.2.0
      - typer==0.16.0
      - types-python-dateutil==2.9.0.20250809
      - typing-inspect==0.9.0
      - typing-inspection==0.4.1
      - uri-template==1.3.0
      - urllib3==2.5.0
      - wandb==0.21.0
      - wasabi==1.1.3
      - watchdog==6.0.0
      - wcwidth==0.2.13
      - weasel==0.4.1
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.14
      - wrapt==1.17.2
      - xxhash==3.5.0
      - yarl==1.20.1
      - zipp==3.23.0
      - zstandard==0.23.0
